main: com.cavetale.warp.WarpPlugin
name: Warp

version: 0.1
api-version: 1.17

description: Warp Plugin
author: StarTux
website: https://cavetale.com

depend: [Core]
softdepend: []

commands:

  warp:
    aliases: []
    description: Use Warps
    permission: warp.warp
    usage: |-
      /warp - List waps
      /warp <name> - Use warp

  setwarp:
    aliases: []
    description: Warp Command
    permission: warp.setwarp
    usage: |-
      /warp

permissions:

  warp.warp:
    description: Use /warp
    default: op

  warp.setwarp:
    description: Use /setwarp
    default: op
