main: com.cavetale.warp.WarpPlugin
name: Warp

version: 0.1
api-version: 1.18

description: Warp Plugin
author: StarTux
website: https://cavetale.com

depend: [Core, SQL, Mytems]
softdepend: []

commands:

  warp:
    aliases: [warps]
    description: Use Warps
    permission: warp.warp
    usage: /warp

  warpadmin:
    aliases: [warpadm]
    description: Admin Command
    permission: warp.admin
    usage: /warpadmin

permissions:

  warp.warp:
    description: Use /warp
    default: op

  warp.admin:
    description: Use /warpadmin
    default: op
